=== SteveChapmanNZ/jradiusserver/bin/radius/server/RadiusServerCfg.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT server (jmx,listens,dispatchStrategy?,filters?,services,connectionProvider,property*)>
<!ATTLIST server type (nio|trade) #REQUIRED>
<!ELEMENT jmx EMPTY>
<!ATTLIST jmx
	enable (true|false) #REQUIRED
	ip CDATA #IMPLIED
	port CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT listens (listen+)>
<!ELEMENT listen EMPTY>
<!ATTLIST listen
	ip CDATA #IMPLIED
	port CDATA #REQUIRED
	type CDATA #REQUIRED
>

<!ELEMENT filters (filter*)>
<!ELEMENT filter (property+)>
<!ATTLIST filter class CDATA #REQUIRED>

<!ELEMENT service (property+)>
<!ATTLIST service class CDATA #REQUIRED>
<!ELEMENT services (service+)>

<!ELEMENT connectionProvider (property+)>
<!ATTLIST connectionProvider class CDATA #REQUIRED>
<!ELEMENT dispatchStrategy EMPTY>
<!ATTLIST dispatchStrategy
	autoConfig (true|false) #REQUIRED
	increment CDATA #IMPLIED
	maxThread CDATA #IMPLIED
	minThread CDATA #IMPLIED
	singleThread (true|false) #REQUIRED
>


<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>

=== SteveChapmanNZ/jradiusserver/trunk/bin/RadiusServerCfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server PUBLIC "-//Radius/Radius Server DTD//EN"
                                         "http://todo.com/RadiusServerCfg.dtd">
<server type="nio">
	<jmx enable="true" ip="localhost" port="508" type="http"/>
	<listens>
		<listen type="auth" ip="localhost" port="1812"/>
		<listen type="account" ip="localhost" port="1813"/>
	</listens>
	<dispatchStrategy singleThread="false" autoConfig="false" minThread="2" maxThread="10" increment="2"/>

	<filters>
		<!--
		<filter class="radius.server.filter.IdFilter">
			<property name="p1"></property>
			<property name="p2"></property>
		</filter>
		-->
		<filter class="radius.server.filter.FormatCheckFilter">
			<property name="p"></property>
			<property name="p2"></property>
		</filter>
	</filters>
	<services>
		<service class="radius.server.service.AuthService">
			<property name="p"></property>
			<property name="p2"></property>
		</service>
		<service class="radius.server.service.AccountService">
			<property name="p"></property>
			<property name="p2"></property>
		</service>
	</services>
	
	<connectionProvider class="radius.connection.SimpleConnectionProvider">
		<property name="driver">com.mysql.jdbc.Driver</property>
		<property name="url">jdbc:mysql://localhost/radius</property>
		<property name="user">root</property>
		<property name="password"></property>
		<property name="minSize">0</property>
		<property name="maxSize">10</property>
		<property name="increment">1</property>
	</connectionProvider>
	
	<property name="radius.server.service.persist.impl">
		radius.server.service.impl.PersistImplProxy
	</property>
	
</server>
